# Change these first
owner: Digifact-FEL
repo: uptime_monitoring
user-agent: gsantovena

sites:
  - name: Digifact Guatemala
    url: https://felgtaws.digifact.com.gt
  - name: Digifact Panama
    url: https://tf.digifact.com.pa
  - name: Marge Datascan
    url: https://marge.datascan-site.com

assignees:
  - gsantovena

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  ##cname: demo.upptime.js.org
  baseUrl: /uptime_monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Digifact Status
  introTitle: "**Digifact** status."
  introMessage: Digifact status for Guatemala, Panamá, and email service.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
